config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # get '/profile', to: 'pages#profile', as: :profile
  resources :profiles, :except => [:index, :destroy]
  resources :kondos do
    resources :bookings, :except => [:index] do
      resources :reviews, :only => [:create]
    end
  end

  get "/bookings", to: "bookings#index"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="container-fluid" id="footer">
  <div class="row d-flex justify-content-between bg-light p-5">
      <div class="col-lg-4">
          <h3>Kondo <i class="far fa-copyright fa-xs" style="font-size: 1rem"></i></h3>
          <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eaque aliquam neque, iste commodi cum autem quam et sed illo consequuntur!</p>
      </div>

    <div class="row m-0 col-lg-6">
      <div class="col-lg-4 col-md-6 col-sm-4">
          <h5>Our Service</h5>
          <ul>
            <li>About us</li>
            <li>Our Work</li>
            <li>Pricing</li>
            <li>Help Center</li>
          </ul>
      </div>

      <div class="col-lg-4">
          <h5>Company</h5>
          <ul>
            <li>Terms of Use</li>
            <li>Contact Us</li>
          </ul>
      </div>

      <div class="col-lg-4">
          <h5>Follow Us</h5>
          <ul>
            <li>Facebook</li>
            <li>Linkedn</li>
            <li>Github</li>
            <li>Twitter</li>
          </ul>
      </div>
    </div>
  </div>
  <div class="d-flex row justify-content-between align-items-center bg-white">
    <div class="col-sm-3 pt-3 text-left">
      <p><small>Made with <i class="far fa-heart"></i> by De.Bored Team <i class="fas fa-at"></i> Le Wagon</small></p>
    </div>
    <div class="col-sm-3 pt-3 text-right">
      <p><small><i class="far fa-copyright"></i> is-kondo.herokuapp.com</small></p>
    </div>

  </div>
</div>

app/views/shared/_navbar.html.erb
  <nav class="navbar navbar-light bg-light justify-content-between px-4">
    <%= link_to root_path, class:"navbar-brand" do %>
    <%= image_tag "https://res.cloudinary.com/djlvhfuba/image/upload/v1643111463/development/kondo-logo.png", class:"img-fluid", style: "width: 100px;" %>
  <% end %>
  <div id="open-nav">
    <% unless current_user.nil? %>
     <%= cl_image_tag current_user.user_photo %>
    <% else %>
      <%= image_tag "https://res.cloudinary.com/djlvhfuba/image/upload/v1643138540/development/user_icon_hqeugo.png", style: "opacity: 0.6" %>
    <% end %>
  </div>
</nav>

app/views/shared/_navbar_homepage.html.erb
 <nav class="navbar navbar-light bg-transparent justify-content-between" style="position: absolute; z-index:10;">
 <div class="d-flex justify-content-between" style="width: 95vw">
    <%= link_to root_path, class:"navbar-brand" do %>
        <%= image_tag "https://res.cloudinary.com/djlvhfuba/image/upload/v1644023482/development/kondo2-logo_rgf7ky.png", style: "width: 175px; padding: 32px 0 0 32px;" %>
     <% end %>
  <div id="open-nav" style= "text-align:center; height: 90px; width: 150px; padding: 32px 32px 0 0;">
    <% unless current_user.nil? %>
     <%= cl_image_tag current_user.user_photo %>
    <% else %>
      <%= image_tag "https://res.cloudinary.com/djlvhfuba/image/upload/v1643138540/development/user_icon_hqeugo.png", style: "opacity: 0.6" %>
    <% end %>
  </div>
 </div>
</nav>

app/views/shared/_sidebar.html.erb
<div id="mySidenav" class="sidenav">
  <a class="closebtn"><i class="fas fa-times"></i></a>


  <% if current_user != nil %>
    <%= link_to profile_path(current_user.id) do %>
      <i class="far fa-user-circle fa-xs"></i> Profile
    <% end %>
      <% if current_user.renter? %>
        <%= link_to bookings_path do %>
          <i class="fas fa-book-open fa-xs"></i> My Bookings
        <% end %>
      <% else %>
       <%= link_to kondos_path do %>
        <i class="fas fa-magic fa-xs"></i> My Kondo
       <% end %>
      <% end %>
    <% end %>

  <% if user_signed_in? %>
    <%= link_to destroy_user_session_path, method: :delete do %>
      <i class="fas fa-sign-out-alt fa-xs"></i> Log out
    <% end %>
  <% else %>
    <%= link_to new_user_session_path do %>
      <i class="fas fa-sign-in-alt fa-xs"></i> Log in
    <% end %>
    <%= link_to new_user_registration_path do %>
      <i class="fas fa-user-plus fa-xs"></i>  Sign up
    <% end %>
  <% end %>
</div>