config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # get '/profile', to: 'pages#profile', as: :profile
  resources :profiles, :except => [:index, :destroy]
  resources :kondos do
    resources :bookings, :except => [:index] do
      resources :reviews, :only => [:create]
    end
  end

  get "/bookings", to: "bookings#index"
end

app/models/kondo.rb
class Kondo < ApplicationRecord
  belongs_to :user
  has_many :users, through: :bookings
  has_many :bookings # no dependent: :destroy, provider can't delete services with pending bookings
  has_one_attached :photo
  acts_as_taggable_on :tags

  include PgSearch::Model
    pg_search_scope :global_search,
      against: [ :prefecture ],
      associated_against: {
        tags: [:name]
      },
      using: {
        tsearch: {any_word: true}
      }

  $categories = ["designers", "keepers", "others"]
  $prefectures = %w[Chiba Kyoto Osaka Tokyo]

  validates :name, :summary, :details, :service_duration, presence: true
end

app/controllers/kondos_controller.rb
class KondosController < ApplicationController
  before_action :set_kondo, only: %i[show edit update destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    # For unauthenticated users and renters
    if !user_signed_in? || current_user.renter?
      @kondos = policy_scope(Kondo).order(created_at: :desc)

      #Homepage search
      unless params[:search_kondos] == ""
        @kondos = policy_scope(Kondo).where("LOWER(prefecture) like ?","%#{params[:search_kondos].to_s.downcase}%")
      else
        @kondos = policy_scope(Kondo).all
      end

      #Index tab search

      if params[:search]
         @filter = params[:search]["tags"].push(params[:search]["prefecture"]).flatten.reject(&:blank?)
         @kondos = policy_scope(Kondo).all.global_search("#{@filter}")
      else
         @kondos = policy_scope(Kondo).all
      end
    # Provider's Page
    else
      @kondos = policy_scope(Kondo).where(user_id: current_user.id)

      # Retrieve only WAITING and CONFIRMED bookings associated to the kondos of that specific user
      @bookings = Booking.where(kondo_id: @kondos, status: ['waiting', 'confirmed'])

      # Transform the bookings in markers
      @markers = @bookings.geocoded.map do |booking|
      {
        lat: booking.latitude,
        lng: booking.longitude,
        info_window: render_to_string(partial: "info_window", locals: { booking: booking }),
        image_url: helpers.asset_url('house-logo.png')
      }
      end
    end

    respond_to do |format|
      format.html
      format.js
    end

  end

  def show
    @kondo = Kondo.find(params[:id])
    @booking = Booking.new
    @review = Review.new
    authorize @kondo

    # returns a hash loaded with information
    # user_type: "renter" / "provider" / "visitor"
    # booking:
    #   from kondo index or home page: most recent booking(object) of the renter for @kondo, nil if user is visitor or provider
    #   from bookings index: the booking itself
    # can_review?, can_book?, is_kondo_creator?: boolean
    # book_now: "Book again!" / "Book now!"
    # sample hash for renter that can reivew: { :user_type=>"renter", booking: booking-object, :can_review?=>true,
    # :can_book?=>true, :booking_btn_caption=> "Book now!" or "Book again!", :is_kondo_creator?=>false }

    @user = analyze_user(@kondo, params[:booking_id])

    if @user[:user_type] == "renter"
      # past bookings of the renter specific for this kondo
      past_bookings = Booking.where(kondo: @kondo, user: current_user)
      # find reviews done by the renter for this specific kondo
      @reviews = Review.where(booking: past_bookings).order(created_at: :desc)
    end
  end

  def new
    @kondo = Kondo.new
    authorize @kondo
  end

  def edit
    authorize @kondo
  end

  def create
    @kondo = Kondo.new(kondo_params)
    @kondo.user_id = current_user.id

    authorize @kondo

    if @kondo.save
      redirect_to kondo_path(@kondo), notice: 'Kondo was successfully created.'
    else
      render :new
    end
  end

  def update
    authorize @kondo

    @kondo.update(kondo_params)

    if @kondo.save
      redirect_to kondo_path(@kondo), notice: 'Kondo was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    authorize @kondo

    @kondo.destroy
    redirect_to kondos_path, notice: 'Kondo was successfully destroyed.'
  end

  private

  def set_kondo
    @kondo = Kondo.find(params[:id])
  end

  def kondo_params
    params.require(:kondo).permit(:name, :summary, :details, :prefecture, :price, :tag_list)
  end

  # TODO: can add as helper method to be more dry
  def analyze_user(kondo, booking_id)
    if user_signed_in?
      if current_user.renter?
        user_type = "renter"

        # get_the_right_booking will return either: the most recent booking for a specific kondo / the booking from booking index page
        booking = get_the_right_booking(kondo, booking_id)
        # find out if the user already made a review for the most recent completed booking of this kondo
        has_been_reviewed = Review.find_by(booking: booking)

        # check if there is a most recent booking
        if booking.present?

          # check if most recent booking status is completed
          if booking.completed?
            # show booking status instead of booking form
            can_book = true
            # booking form button as `Book again!` instead of `Book now!`
            book_now = false

            # use this flag to show review form if there are now reviews yet
            can_review = true if !has_been_reviewed
          else
            # this else block means booking status is not `completed`
            if booking.declined?
              can_book = true
              # method returns a boolean, true if renter had a completed booking of this kondo before, else false
              book_now = has_completed_a_booking_before
            end
            # this block means that the status is either `waiting` or `confirmed`, no code needed
            # we show booking status instead of booking form, renter can't book, can_book is false by default
          end
        else
          # this block means renter has never booked this kondo, booking.present? is nil
          can_book = true
          book_now = true
        end
      else
        # this block means user is a provider
        user_type = "provider"
        # find out if provider is the creator of the kondo
        is_kondo_creator = current_user.id == kondo.user.id
      end
    else
      user_type = "visitor"
      can_book = true
      book_now = true
    end

    # method returns this hash
    {
      # value after || will be used if value on left is nil
      user_type: user_type,
      booking: booking,
      can_review?: can_review || false,
      can_book?: can_book || false,
      booking_btn_caption: book_now ? "Book now!" : "Book again!",
      is_kondo_creator?: is_kondo_creator || false
    }
  end

  def get_the_right_booking(kondo, booking_id)
    if booking_id.present?
      # a renter clicks `See Details` from Bookings Index page
      Booking.find(booking_id)
    else
      # a user (renter/visitor/provider) clicks `See Details` from Kondo Index page
      # find most recent booking of renter for the kondo in the argument
      Booking.where(user: current_user, kondo: kondo).order(created_at: :asc).first
    end
  end

  def has_completed_a_booking_before
    # find all bookings for current user and  get the unqiue status of the bookings
    bookings = Booking.where(user: current_user).map(&:status).uniq
    # return true if the user has completed at least one booking
    bookings.include?("completed")
  end
end

app/views/kondos/_booking_form.html.erb
<div id="booking-form" class="col-lg-4 col-sm-12 p-4 m-2">
  <h3>Make a Reservation</h3><br>
  <h5><strong>￥<%= @kondo.price %></strong> <small>/ session</small></h5>
  <%= simple_form_for([@kondo, @booking]) do |f| %>
    <div class="d-flex flex-column">
      <%= f.date_field :booked_date, min: Date.today + 3, as: :date, html5: true, error: false, class: "p-1 my-2" %>
      <%= f.input :address, id: 'booking_address' %>
      <%= f.submit "#{@user[:booking_btn_caption]}", class:"btn btn-primary my-2", id:"submit-btn" %>
      <%= f.error :booked_date, style: "color:red" %>
    </div>
  <% end %>
</div>

app/views/kondos/_booking_status.html.erb
<div id="booking-form" class="col-lg-4 col-sm-12 p-4 m-2">
  <h3>Current booking status:</h3>
  <h3><%= @user[:booking].status.capitalize %></h3>
</div>

app/views/kondos/_bookings_for_provider.html.erb
<div class="container">
  <h4>People who currently booked this Kondo:</h4>
    <div class="row">
      <% @kondo.bookings.each do |booking| %>
        <div class="col-lg-4 col-md-6 col-sm-12 bg-white p-4 m-2">
          <p>Renter: <%= User.find(booking.user_id).first_name %></p>
          <p>Booked Date: <%= booking.booked_date %></p>
          <%= simple_form_for ([@kondo, booking]), remote: true  do |f| %>
            <div class="d-flex align-items-center">
              <%= f.input :status, :collection => ['waiting','confirmed','declined','completed'], label: false %>
              <%= f.submit "Update Status", class: "btn btn-success" %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
</div>

app/views/kondos/_form.html.erb
<%= simple_form_for(kondo) do |f| %>
  <%= f.input :name, collection: ["Commercial Interior Designer", "Space Planning Interior Designer", "Minimalist Interior Designer",
  "Professional Housekeeper", "Industrial Housekeeping"] %>
  <%= f.input :service_duration %>
  <%= f.input :summary %>
  <%= f.input :details %>
  <%= f.input :prefecture, collection: %w[Aichi Akita Aomori Chiba Ehime Fukui Fukuoka Fukushima Gifu Gunma Hiroshima Hokkaido Hyogo Ibaraki Ishikawa Iwate Kagawa Kagoshima Kanagawa Kochi Kumamoto Kyoto Mie Miyagi Miyazaki Nagano Nagasaki Nara Niigata Okayama Okinawa Oita Osaka Saga Saitama Shiga Shimane Shizuoka Tochigi Tokushima Tokyo Tottori Toyama Wakayama Yamagata Yamaguchi Yamanashi] %>
  <%= f.input :price %>
  <%= f.submit "Create Kondo", class: "btn btn-primary" %>
<% end %>

app/views/kondos/_info_window.html.erb
<% kondo = Kondo.find(booking.kondo_id) %>
<% user = User.find(booking.user_id) %>
<h4><%= kondo.name %></h4>
<p>Booked by <%= user.first_name %> <%= user.last_name %> on <%= booking.booked_date %></p>

app/views/kondos/_kondo_index.html.erb
<div class="row justify-content-end">
  <div class="col-10">
    <div class="row">
      <% kondos.each do |kondo| %>
        <div class="col-xl-3 col-md-6 col-sm-12 d-flex justify-content-center">
            <%= render "components/cardRenter",
                photo: kondo.user.user_photo,
                name:  kondo.user.first_name,
                price: kondo.price,
                summary: kondo.summary.split(" ").first(10).join(" "),
                kondo: kondo.name,
                prefecture: kondo.prefecture,
                path: kondo_path(kondo)
            %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/kondos/_review_form.html.erb
<div id="booking-form" class="col-lg-8 col-sm-12 p-4 m-2">
  <h3>Share your experience about this Kondo</h3><br>
  <%= simple_form_for([@kondo, @user[:booking], @review]) do |f| %>
    <div class="d-flex flex-column">
      <%= f.input :rating, as: :integer %>
      <%= f.input :comment %>
      <%= f.submit "Submit review", class: "btn btn-primary my-2" %>
    </div>
  <% end %>
</div>

app/views/kondos/_submitted_reviews.html.erb
<div id="booking-form" class="container">
  <h3 class="pt-4">Reviews</h3>
  <ul class="list-group list-group-flush">
    <% reviews.each do |review| %>
      <li class="list-group-item">
        <h5>By <%= review.user.first_name %>, on <%= review.booking.kondo.name %> </h5>
        <p>Rating: <%= review.rating %></p>
        <p>Comment: <%= review.comment %> </p>
      </li>
    <% end %>
  </ul>
</div>

app/views/kondos/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-6 col-md-6 col-sm-12">
        <h4>Edit Kondo</h4>
        <%= render "form", kondo: @kondo %>
    </div>
  </div>
</div>

app/views/kondos/index.html.erb
<!-- Delete h1 later !-->
<div class="container">
  <% if user_signed_in? && current_user.provider? %>
    <h2> My Kondos <small>(<%= @kondos.count %>)</small></h2>
    <%= link_to "Add new Kondo", new_kondo_path, class: "btn btn-warning"  %>
    <div class="row">
    <% @kondos.each do |kondo| %>
      <div class="col-xl-3 col-md-6 col-sm-12 d-flex justify-content-center">
        <% all_bookings = kondo.bookings.where(status: ['waiting', 'confirmed']).count%>
          <% if all_bookings == 0 %>
            <%= render "components/cardProviderNoBadge",
              price: kondo.price,
              summary: kondo.summary.split(" ").first(10).join(" "),
              kondo: kondo.name,
              prefecture: kondo.prefecture,
              path: kondo_path(kondo)
            %>
          <% else %>
            <%= render "components/cardProvider",
              book: all_bookings,
              price: kondo.price,
              summary: kondo.summary.split(" ").first(10).join(" "),
              kondo: kondo.name,
              prefecture: kondo.prefecture,
              path: kondo_path(kondo)
            %>
          <% end %>
        </div>
      <% end %>

      <!-- Map for providers -->
      <div id="map"
            style="width: 100%; height: 600px;"
            data-markers="<%= @markers.to_json %>"
            data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
  </div>

  <% else  %>

    <!-- For renters and unauthenticated users -->
    <div id="side-filter">
      <%= render  "components/search_index", filter: :search, path: kondos_path %>
    </div>
    <div id="kondos">
      <%= render "kondo_index", kondos: @kondos %>
    </div>
  <% end %>
</div>

app/views/kondos/index.js.erb
var replaceKondos = (innerHTML) => {
  const kondos = document.getElementById('kondos');
  kondos.innerHTML = innerHTML;
}
replaceKondos("<%= j render 'kondo_index', kondos: @kondos %>");

if ('<%= @filter %>' === "[]") {
    replaceKondos("<%= j render 'kondo_index', kondos: Kondo.all %>");
}
else {
    replaceKondos("<%= j render 'kondo_index', kondos: @kondos %>");
}

app/views/kondos/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-6 col-md-6 col-sm-12">
        <h4>Create your Kondo</h4>
        <%= render "form", kondo: @kondo %>
    </div>
  </div>
</div>

app/views/kondos/show.html.erb
<div class="container">
  <div class="row justify-content-around">
    <div id="booking-form" class="col-lg-6 col-sm-12 p-4 m-2" style="background: white;">
      <div class="row text-center">

        <div class="col-lg-4 col-sm-4">
          <%= link_to profile_path (@kondo.user.profile_id) do %>
            <%= cl_image_tag @kondo.user.user_photo, style: "width: 200px; height: 200px; object-fit: cover; border-radius: 50%;"%>
          <% end %>
        </div>

        <div class="col-lg-8 col-sm-6 align-self-center">
          <%= link_to profile_path (@kondo.user.profile_id) do %>
            <h3><%= @kondo.user.first_name %> <%= @kondo.user.last_name %></h3>
          <% end %>
          <h5><%= @kondo.name %></h5>
        </div>
      </div>

      <%# --- Start of Kondo Details --- %>
      <div class="row">
        <div class="col-12 py-5">
          <h4>Details</h4>
          <p><%= @kondo.details %></p>
        </div>
        <%# Only the provider who created the kondo can see this %>
        <% if @user.present? && @user[:is_kondo_creator?] %>
          <div class="col-12 d-flex justify-content-between">
            <%= link_to "Edit", edit_kondo_path(@kondo), style: "color: green" %>
            <%= link_to "Delete", kondo_path(@kondo), method: :delete, data: { confirm: "Are you sure?" }, style: "color: red" %>
          </div>
        <% end %>
      </div>
      <%# --- End of Kondo Details --- %>
    </div>

    <%# Review cheat sheet: https://docs.google.com/spreadsheets/d/1wh7T1UGmmVacvZtotEdq9aZ1-9o-BayaYrR3fnfPRWg/edit#gid=0 %>
    <%# Renters can view a kondo and see booking status / book a kondo / leave a review %>
    <% if @user.present? && @user[:user_type] == "renter" %>
      <%# renter can book if they have never booked the kondo yet or if previous booking for the kondo is completed or declined %>
      <% if @user[:can_book?] %>
        <%= render "booking_form" %>
        <%# renter can review if most recent booking status for kondo is completed and if they have not made a review yet %>
        <% if @user[:can_review?] %>
          <%= render "review_form" %>
        <% end %>
      <% else %>
        <%# if renter can't book (if status is waiting or confirmed), show booking status %>
        <%= render "booking_status" %>
      <% end %>
    <% end %>

    <%# Visitors can view a kondo and can make an attempt to book a kondo %>
    <% if @user.present? && @user[:user_type] == "visitor" %>
      <%= render "booking_form" %>
    <% end %>

    <%# Only shows up for renters who have left a review on their completed bookings if there is at least one review for this kondo %>
    <% if @reviews.present? && !@reviews.count.zero? %>
      <%= render "submitted_reviews", reviews: @reviews %>
    <% end %>
  </div>
</div>



<%# Only the provider who created the kondo can see this %>
<% if @user.present? && @user[:is_kondo_creator?] %>
  <%= render "bookings_for_provider" %>
<% end %>